### ISSUE TITLE
pom.xml  有问题吧

### ISSUE THREAD

**Issue by nocb** [dinghuang/activiti-service#2]
<parent>
        <artifactId>dinghuang-framework-parent</artifactId>
        <groupId>org.dinghuang</groupId>
        <version>0.1.0-RELEASE</version>
    </parent> 

找不到

**Comment by dinghuang** [comment]
这个是我自己封装的，在我私人的nexus上面，这个不重要，不过你可以看一下这个https://github.com/dinghuang/spring-cloud-framework
